### ISSUE TITLE
Crash during world load on VS 1.15.3 due to Harmony patch

### ISSUE THREAD

**Issue by gnalvesteffer** [91loocekaj/vs-usefulstuff#1]
Stack Trace:
```
Version: v1.15.3 (Stable)2021-08-03 6:55:51 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.Common.CreativeTab.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Common.CreativeTabs.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GuiManager.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.ClientMain.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(_eOG09N3CughgUhSOBaTcUtF8rXW packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _2C1KeYAVBdmrSIvSFhy6H2IB73P._VmVAOpmA6roNiWQoNAQLt9tWkzR(Single )
   at _0h7dYtC5OxgFq3Dhnj2p0gxEXO3._7siDwGtIPuCnT2TllZ2WXtr1bsM(Single )
   at _0h7dYtC5OxgFq3Dhnj2p0gxEXO3._YznPHQWtIAwbLwxdlknpXY2Mrsm(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _Km7YT9SY1sKIj5UBhEpQfHc3XzB._u0WbDJ5hzkzp3qHp31dGQ3NRIqJ(_EyrNhzlOC9XfxRuKJ1Vc8VeXIpA , String[] )
   at _pFLYUi2IEGEC895yDwFlhWqtVoD._u0WbDJ5hzkzp3qHp31dGQ3NRIqJ(ThreadStart )
```

**Comment by 91loocekaj** [comment]
I can load up into my world just fine on 1.15.3, I don't have any patches on the base CollectibleObject held info method, and that crash does not point to a Harmony patch. Are you sure it is coming from this mod, and if so what item is causing this?
