### ISSUE TITLE
Crash when loading world due to MCB: Stone Pickaxes on version 1.15.5

### ISSUE THREAD

**Issue by Npcfanatic21** [91loocekaj/vs-usefulstuff#2]
heres the log - 

Running on 64 bit Windows with 32 GB RAM 
Version: v1.15.5 (Stable)8/29/2021 10:33:55 PM: Critical error occurred
System.NullReferenceException: Object reference not set to an instance of an object.
   at Vintagestory.API.Common.CollectibleObject.GetHeldItemInfo(ItemSlot inSlot, StringBuilder dsc, IWorldAccessor world, Boolean withDebugInfo)
   at Vintagestory.Common.CreativeTab.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Common.CreativeTabs.CreateSearchCache(IWorldAccessor world)
   at Vintagestory.Client.NoObf.GuiDialogInventory.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GuiManager.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.ClientMain.OnOwnPlayerDataReceived()
   at Vintagestory.Client.NoObf.GeneralPacketHandler.HandlePlayerData(_K0gsRhlFmzAJ65AP27fyOAZKCbA packet)
   at Vintagestory.Client.NoObf.ClientMain.ExecuteMainThreadTasks(Single deltaTime)
   at _TKxd5zsRGjdjjLt43mszZSMKrNM._ra0MgpFbqkfgNETNlZ5CppyVnhE(Single )
   at _Wwq7msw90Af4XU7mxkxAUKyrS5B._iIGaTXNE8VYTpgEu9zjpAQyJSxd(Single )
   at _Wwq7msw90Af4XU7mxkxAUKyrS5B._vCB99EztL7cSfmplK8tyTwrQQxC(Single )
   at Vintagestory.Client.NoObf.ClientPlatformWindows.window_RenderFrame(Object sender, FrameEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OpenTK.GameWindow.RaiseRenderFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchRenderFrame()
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at _q065sSmA3CNgGuKTGnlAjR4ljPw._WkSl7yfiyr5DwPiSMvTudNAhp6(_t3ILnyYBq5OoYhhBY3JeTWgFmJDA , String[] )
   at _DBu5wiQWRAHGS5G2jiCKymvQ9yE._WkSl7yfiyr5DwPiSMvTudNAhp6(ThreadStart )

**Comment by 91loocekaj** [comment]
This should be fixed by now.
